default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: my_basecamp_2_development
  username: my_basecamp_2
  password: 'let me in'
  host: localhost
  port: 5432

test:
  <<: *default
  database: my_basecamp_2_test
  username: my_basecamp_2
  password: 'let me in'
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cache:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

queue:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: my_basecamp_2_development
#   username: my_basecamp_2
#   password: 'let me in'
#   host: localhost
#   port: 5432

# test:
#   <<: *default
#   database: my_basecamp_2_test
#   username: my_basecamp_2
#   password: 'let me in'
#   host: localhost
#   port: 5432

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: my_basecamp_kpbi
#   username: my_basecamp_kpbi_user
#   password: bsdIIjrjlNltH5khauBvbjDNQ2ALlTln
#   host: dpg-d00jciali9vc739vrq2g-a.oregon-postgres.render.com
#   port: 5432
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000


# cache:
#   <<: *default
#   url: <%= ENV["DATABASE_URL"] %>

# cable:
#   <<: *default
#   url: <%= ENV["DATABASE_URL"] %>

# queue:
#   <<: *default
#   url: <%= ENV["DATABASE_URL"] %>
